services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        ports:
            - '9000:9000'
        depends_on:
            - db
            - node
    db:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        ports:
            - '3306:3306'
    node:
        image: node:16
        container_name: node
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
volumes:
    dbdata:
networks:
    app-network:
        driver: bridge
